new deployment settings generation

diff --git a/.activate.template b/.activate.template
--- a/.activate.template
+++ b/.activate.template
@@ -1,20 +1,19 @@
-export PUNCHBOX_DIR=/home/cedric/lmc/pp-punchbox
+# punchbox env
+export PUNCHBOX_DIR=/tmp
+export PUNCHBOX_DEPLOYERS_DIR="${PUNCHBOX_DIR}/deployers"
+export PUNCHBOX_VAGRANT_DIR="${PUNCHBOX_DIR}/punch/vagrant"
 export PUNCHBOX_BUILD_DIR="${PUNCHBOX_DIR}/punch/build"
-export PUNCHPLATFORM_CONF_DIR="${PUNCHBOX_BUILD_DIR}"/pp-conf
-export PATH="${PUNCHBOX_DIR}/bin:${PUNCHBOX_DIR}/bin/pex/ansible_pex:$PATH"
-export PS1='\[[1;32m\]punchbox:\[[0m\][\W]$ '
-mkdir -p "${PUNCHBOX_BUILD_DIR}"
+export PUNCHBOX_TEMPLATES_DIR="${PUNCHBOX_DIR}/punch/templates"
+export PUNCHPLATFORM_CONF_DIR="${PUNCHBOX_BUILD_DIR}/pp-conf"
 
-# Looking for unziped deployer (if it exists)
-export PUNCHBOX_DEPLOYER_DIR=""
-for deployer in $(cd "${PUNCHBOX_BUILD_DIR}" ; ls -ltrd */ 2>null | grep 'punch.*-deployer-.*' 2>null) ; do
-   PUNCHBOX_DEPLOYER_DIR="${PUNCHBOX_BUILD_DIR}/${deployer}"
-done
-
-if [ "${PUNCHBOX_DEPLOYER_DIR:-}" = ""  ] ; then
-	echo "No deployer unzipped."
+# punchbox deployer
+if [ "${PUNCHBOX_DEPLOYER}" = ""  ] ; then
+	echo "FATAL: Missing PUNCHBOX_DEPLOYER environment variable"
+	exit 1
 else
-	echo "Using deployer '${PUNCHBOX_DEPLOYER_DIR}'..."
-	export PATH="${PUNCHBOX_DEPLOYER_DIR}/bin:${PATH}"
+	echo "Using deployer '${PUNCHBOX_DEPLOYER}'"
 fi
 
+# punchbox path
+export PATH="${PUNCHBOX_DIR}/bin:${PUNCHBOX_DEPLOYER}/bin:$PATH"
+#export PS1='\[[1;32m\]punchbox:\[[0m\][\W]$ '
